
# Groq API key  https://console.groq.com/keys
groq.api.key=YOUR_GROQ_API_KEY_HERE



# Minimum milliseconds between Groq API calls.
groq.min.interval.ms=2500

# Documented default WildFly HTTP port (for Postman);
server.port=8080
